apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume-shalmali
  namespace: jagan
  labels:
    type: local
spec:
  storageClassName: mysql-shalmali
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data-shalmali"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim-shalmali
  namespace: jagan
spec:
  storageClassName: mysql-shalmali
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi